# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TCIAClient": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://moritzschwyzer.github.io/tciaclient/"

git_url = "https://github.com/moritzschwyzer/tciaclient/tree/master/"

def custom_doc_links(name): return None
